Repository whatever-mentoring/SeulSeul_Android, pull requests merged in 2023-10, with the labels that each got.

#98 Feature/network https mj
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
Labels: 명지, feat

#101 [FIX] baserouteId 0L아닐때 post보내지게
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
Labels: 현배, fix

#102 [FIX] @get /v1/end/{id} 500 에러 해결
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
Labels: 명지, fix

#104 Feature/get end id error fix
  app/src/main/java/com/timi/seulseul/MainApplication.kt
  app/src/main/java/com/timi/seulseul/data/api/ApiService.kt
  app/src/main/java/com/timi/seulseul/data/repository/SetEndLocationRepo.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/viewmodel/LocationDetailViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/main/adapter/SubwayRouteAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingAdapter.kt
Labels: 명지, fix

#106 Feature/location set toast
  app/src/main/AndroidManifest.xml
  app/src/main/ic_seulseul_app-playstore.png
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationDetailActivity.kt
  app/src/main/res/drawable/ic_seulseul_app_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_seulseul_app.xml
  app/src/main/res/mipmap-anydpi-v26/ic_seulseul_app_round.xml
  app/src/main/res/mipmap-hdpi/ic_seulseul_app.webp
  app/src/main/res/mipmap-hdpi/ic_seulseul_app_round.webp
  app/src/main/res/mipmap-mdpi/ic_seulseul_app.webp
  app/src/main/res/mipmap-mdpi/ic_seulseul_app_round.webp
  app/src/main/res/mipmap-xhdpi/ic_seulseul_app.webp
  app/src/main/res/mipmap-xhdpi/ic_seulseul_app_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_seulseul_app.webp
  app/src/main/res/mipmap-xxhdpi/ic_seulseul_app_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_seulseul_app.webp
  app/src/main/res/mipmap-xxxhdpi/ic_seulseul_app_round.webp
  app/src/main/res/values/ic_seulseul_app_background.xml
Labels: 명지, feat

#107 Feature/total logic
  app/src/main/java/com/timi/seulseul/data/model/DayInfo.kt
  app/src/main/java/com/timi/seulseul/data/model/RealDayInfo.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/common/adapter/BindingAdapter.kt
  app/src/main/res/layout/activity_main.xml
Labels: 예빈, feat

#108 Feature/fcm check
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/data/model/SubwayRouteItem.kt
  app/src/main/java/com/timi/seulseul/data/service/FirebaseService.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/common/adapter/BindingAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/common/constants/Const.kt
  app/src/main/java/com/timi/seulseul/presentation/dialog/AlarmBottomSheetFragment.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationDetailActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationSearchActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/main/activity/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/main/adapter/SubwayRouteAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/item_subway_body_info.xml
  app/src/main/res/layout/item_subway_transfer.xml
Labels: 예빈, feat

#110 Feature/edit refresh distance
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
Labels: 예빈, chore

#112 Feature/coroutine delay
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
  app/src/main/java/com/timi/seulseul/presentation/main/activity/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_network_check.xml
  app/src/main/res/layout/layout_subway_route_title_bar.xml
  app/src/main/res/values/strings.xml
Labels: 예빈, chore

#114 Feature/permission text fix
  app/src/main/res/layout/activity_permission.xml
  app/src/main/res/values/strings.xml
Labels: 예빈, chore

#116 Feature/edit version code
  app/build.gradle.kts
Labels: 예빈, chore

#118 Feature/edit rejects
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_seulseul-playstore.png
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
  app/src/main/java/com/timi/seulseul/presentation/setting/SettingActivity.kt
  app/src/main/res/drawable/ic_seulseul_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_seulseul.xml
  app/src/main/res/mipmap-anydpi-v26/ic_seulseul_round.xml
  app/src/main/res/mipmap-hdpi/ic_seulseul.webp
  app/src/main/res/mipmap-hdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-mdpi/ic_seulseul.webp
  app/src/main/res/mipmap-mdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xhdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xxhdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xxxhdpi/ic_seulseul_round.webp
  app/src/main/res/values/ic_seulseul_background.xml
  app/src/main/res/values/strings.xml
Labels: 예빈, chore

#120 Feature/version code fix
  app/build.gradle.kts
Labels: 예빈, chore

#122 Feature/change app icon
  app/build.gradle.kts
  app/src/main/ic_seulseul-playstore.png
  app/src/main/res/drawable/ic_seulseul.xml
  app/src/main/res/drawable/ic_seulseul_foreground.xml
  app/src/main/res/mipmap-hdpi/ic_seulseul.webp
  app/src/main/res/mipmap-hdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-mdpi/ic_seulseul.webp
  app/src/main/res/mipmap-mdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xhdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xxhdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xxxhdpi/ic_seulseul_round.webp
  app/src/main/res/values-v26/themes.xml
  app/src/main/res/values-v31/themes.xml
Labels: 예빈, chore
