Repository whatever-mentoring/SeulSeul_Android, pull requests merged in 2023-09, with the labels that each got.

#3 Feature/project setting
  .gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/MainApplication.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/common/base/BaseActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/common/base/BaseFragment.kt
  app/src/main/java/com/timi/seulseul/presentation/common/base/BaseViewModel.kt
  app/src/main/res/font/font.xml
  app/src/main/res/font/pretendard_black.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_extra_bold.otf
  app/src/main/res/font/pretendard_extra_light.otf
  app/src/main/res/font/pretendard_light.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semi_bold.otf
  app/src/main/res/font/pretendard_thin.otf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle.properties
Labels: 예빈, feat

#8 UI/권한 허용 페이지 뷰 작업(와이어프레임 기반)
  app/src/main/res/layout/activity_permission.xml
  app/src/main/res/values/strings.xml
Labels: 명지, ui

#11 Feature/subway route UI
  app/src/main/res/drawable/img_circle_station_50.xml
  app/src/main/res/drawable/img_dotted_line.xml
  app/src/main/res/drawable/rotate_dotted_line_vertical.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_subway_header.xml
  app/src/main/res/layout/item_subway_line.xml
  app/src/main/res/layout/item_subway_transfer.xml
Labels: 예빈, ui

#18 Feature/permission edit
  app/src/main/res/layout/activity_permission.xml
  app/src/main/res/values/strings.xml
Labels: 명지, ui

#19 Feature/alarm setting UI
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/dialog/AlarmBottomSheetFragment.kt
  app/src/main/res/drawable/bg_white_r40.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_alarm_bottom_sheet_dialog.xml
  app/src/main/res/values/themes.xml
Labels: 예빈, ui

#21 Feature/permission location
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
  app/src/main/res/layout/activity_permission.xml
Labels: 명지, feat

#30 Feature/permission UI
  app/src/main/res/layout/activity_permission.xml
  app/src/main/res/values/strings.xml
Labels: 명지, ui

#32 Feature/network setting
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/data/api/ApiService.kt
  app/src/main/java/com/timi/seulseul/data/model/User.kt
  app/src/main/java/com/timi/seulseul/data/repository/UserRepo.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/apitest/ApiTestActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/apitest/ApiTestViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/common/base/BaseViewModel.kt
  app/src/main/res/layout/activity_apitest.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/xml/network_security_config.xml
  build.gradle.kts
  gradle.properties
Labels: 현배, feat, fix

#29 Feature/permission alarm
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
Labels: 명지, feat

#33 Feature/splash
  app/src/main/AndroidManifest.xml
  app/src/main/ic_seulseul-playstore.png
  app/src/main/res/drawable/ic_seulseul_background.xml
  app/src/main/res/drawable/ic_seulseul_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_seulseul.xml
  app/src/main/res/mipmap-anydpi-v26/ic_seulseul_round.xml
  app/src/main/res/mipmap-hdpi/ic_seulseul.webp
  app/src/main/res/mipmap-hdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-mdpi/ic_seulseul.webp
  app/src/main/res/mipmap-mdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xhdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xxhdpi/ic_seulseul_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_seulseul.webp
  app/src/main/res/mipmap-xxxhdpi/ic_seulseul_round.webp
  app/src/main/res/values-v26/themes.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/splash.xml
  gradle.properties
Labels: 현배, feat

#34 Feature/location search UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/adapter/locationAdapter.kt
  app/src/main/res/drawable/border_location_bottom.xml
  app/src/main/res/drawable/ic_location_detail_home_default.xml
  app/src/main/res/drawable/ic_location_search.xml
  app/src/main/res/layout/activity_location.xml
  app/src/main/res/layout/activity_permission.xml
  app/src/main/res/layout/item_location_detail.xml
  app/src/main/res/values/strings.xml
Labels: 명지, ui

#37 Feature/fcm setting
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/MainApplication.kt
  app/src/main/java/com/timi/seulseul/presentation/FirebaseService.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle.properties
Labels: 예빈, feat

#40 Feature/alarm setting
  app/src/main/java/com/timi/seulseul/MainApplication.kt
  app/src/main/java/com/timi/seulseul/data/model/Alarm.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/dialog/AlarmBottomSheetFragment.kt
  app/src/main/res/drawable/bg_green_500_main_r8.xml
  app/src/main/res/drawable/bg_grey_400_r8.xml
  app/src/main/res/drawable/selector_alarm_preferred_time_check.xml
  app/src/main/res/drawable/selector_alarm_time_term_check.xml
  app/src/main/res/drawable/selector_alarm_time_term_text_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_alarm_bottom_sheet_dialog.xml
  app/src/main/res/layout/layout_alarm_preferred_time.xml
  app/src/main/res/values/strings.xml
Labels: 예빈, feat, ui

#36 Feature/location detail
  app/src/main/res/drawable/bg_black_r4.xml
  app/src/main/res/drawable/ic_location_detail_line.xml
  app/src/main/res/layout/activity_location_detail.xml
  app/src/main/res/layout/activity_permission.xml
  app/src/main/res/layout/item_location_detail.xml
  app/src/main/res/values/strings.xml
Labels: 명지, ui

#42 Feature/location search
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationDetailActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationSearchActivity.kt
  app/src/main/res/layout/activity_location_search.xml
Labels: 명지, feat

#45 Feature/network setting fix
  app/build.gradle.kts
  app/src/main/java/com/timi/seulseul/data/api/ApiService.kt
  app/src/main/java/com/timi/seulseul/data/model/Auth.kt
  app/src/main/java/com/timi/seulseul/data/repository/AuthRepo.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
  gradle.properties
Labels: 현배, feat, fix

#46 Feature/alarm day refresh
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: 예빈, feat

#50 [FEAT] #47 알림 갱신 로직 수정
  app/src/main/java/com/timi/seulseul/data/model/DayInfo.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
Labels: 예빈, feat

#53 [FEAT] #52 v1/start patch
  app/src/main/java/com/timi/seulseul/data/api/ApiService.kt
  app/src/main/java/com/timi/seulseul/data/repository/ErrorUtils.kt
  app/src/main/java/com/timi/seulseul/data/repository/LocationRepo.kt
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
Labels: 현배, feat

#49 Feature/location save
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/data/model/request/LocationRequest.kt
  app/src/main/java/com/timi/seulseul/data/model/response/LocationResponse.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationDetailActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationSearchActivity.kt
Labels: 명지, feat, ui

#55 Feature/fcm token post
  app/src/main/java/com/timi/seulseul/data/api/FcmTokenService.kt
  app/src/main/java/com/timi/seulseul/data/model/response/FcmTokenResponse.kt
  app/src/main/java/com/timi/seulseul/data/model/resquest/FcmTokenRequest.kt
  app/src/main/java/com/timi/seulseul/data/repository/FcmTokenRepo.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/FirebaseService.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionViewModel.kt
  gradle.properties
Labels: 예빈, feat

#58 Feature/location save network
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/MainApplication.kt
  app/src/main/java/com/timi/seulseul/data/api/ApiService.kt
  app/src/main/java/com/timi/seulseul/data/model/request/EndLocationRequest.kt
  app/src/main/java/com/timi/seulseul/data/model/response/EndLocationData.kt
  app/src/main/java/com/timi/seulseul/data/repository/EndLocationRepo.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationDetailActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/viewmodel/LocationDetailViewModel.kt
  app/src/main/res/xml/network_security_config.xml
Labels: 명지, feat

#60 Feature/alarm setting post
  app/src/main/java/com/timi/seulseul/data/api/AlarmService.kt
  app/src/main/java/com/timi/seulseul/data/api/FcmTokenService.kt
  app/src/main/java/com/timi/seulseul/data/model/request/AlarmRequest.kt
  app/src/main/java/com/timi/seulseul/data/model/request/FcmTokenRequest.kt
  app/src/main/java/com/timi/seulseul/data/model/response/AlarmResponse.kt
  app/src/main/java/com/timi/seulseul/data/repository/AlarmRepo.kt
  app/src/main/java/com/timi/seulseul/data/repository/FcmTokenRepo.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionViewModel.kt
Labels: 예빈, feat

#62 Feature/onboarding
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/MainApplication.kt
  app/src/main/java/com/timi/seulseul/data/api/ApiService.kt
  app/src/main/java/com/timi/seulseul/data/model/Location.kt
  app/src/main/java/com/timi/seulseul/data/model/OnBoarding.kt
  app/src/main/java/com/timi/seulseul/data/repository/LocationRepo.kt
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
  app/src/main/res/drawable/img_onboarding1.png
  app/src/main/res/drawable/img_onboarding2.png
  app/src/main/res/drawable/img_onboarding3.png
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/item_on_boarding.xml
Labels: 현배, feat, fix

#64 Feature/alarm setting patch
  app/src/main/java/com/timi/seulseul/data/api/AlarmService.kt
  app/src/main/java/com/timi/seulseul/data/model/request/AlarmPatchRequest.kt
  app/src/main/java/com/timi/seulseul/data/model/request/AlarmPostRequest.kt
  app/src/main/java/com/timi/seulseul/data/model/response/AlarmPatchResponse.kt
  app/src/main/java/com/timi/seulseul/data/model/response/AlarmPostResponse.kt
  app/src/main/java/com/timi/seulseul/data/repository/AlarmRepo.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
Labels: 예빈, feat

#66 Feature/fused location start
  app/src/main/java/com/timi/seulseul/MainApplication.kt
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
Labels: 현배, feat, fix

#67 Feature/fcm on off
  app/src/main/java/com/timi/seulseul/presentation/FirebaseService.kt
Labels: 예빈, feat

#70 Feature/custom dialog UI
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/dialog/LocationBeforeDialogFragment.kt
  app/src/main/res/drawable/bg_white_r8.xml
  app/src/main/res/layout/fragment_location_before_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 예빈, feat, ui

#73 Feature/alarm_setting_post_patch_fix
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/dialog/AlarmBottomSheetFragment.kt
Labels: 예빈, fix

#74 Feature/alarm on off
  app/src/main/java/com/timi/seulseul/data/api/AlarmService.kt
  app/src/main/java/com/timi/seulseul/data/model/response/AlarmEnabledPatchResponse.kt
  app/src/main/java/com/timi/seulseul/data/repository/AlarmRepo.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
Labels: 예빈, feat

#76 Feature/setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/setting/SettingActivity.kt
  app/src/main/res/layout/activity_apitest.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
Labels: 현배, feat

#78 Feature/location select
  app/src/main/java/com/timi/seulseul/data/api/ApiService.kt
  app/src/main/java/com/timi/seulseul/data/model/response/GetEndLocationData.kt
  app/src/main/java/com/timi/seulseul/data/repository/GetEndLocationRepo.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationDetailActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/adapter/BindingAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/location/adapter/locationAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/location/viewmodel/LocationViewModel.kt
  app/src/main/res/layout/activity_location.xml
  app/src/main/res/layout/activity_location_detail.xml
  app/src/main/res/layout/item_location_detail.xml
Labels: 명지, feat

#81 Feature/location select
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/data/api/ApiService.kt
  app/src/main/java/com/timi/seulseul/data/model/User.kt
  app/src/main/java/com/timi/seulseul/data/repository/SetEndLocationRepo.kt
  app/src/main/java/com/timi/seulseul/data/repository/UserRepo.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/apitest/ApiTestActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/apitest/ApiTestViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationDetailActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/adapter/locationAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/location/viewmodel/LocationViewModel.kt
  app/src/main/res/layout/activity_apitest.xml
  app/src/main/res/layout/activity_main.xml
Labels: 명지, feat

#85 [DEL] #84 Apitest 삭제
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
Labels: 명지, fix

#80 Feature/splash check
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/timi/seulseul/Utils.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/img_onboarding1.png
  app/src/main/res/drawable/img_onboarding1_searchbar.png
  app/src/main/res/drawable/img_onboarding2.png
  app/src/main/res/drawable/img_onboarding3.png
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/dialog_network_check.xml
  app/src/main/res/layout/item_on_boarding.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/strings.xml
Labels: 현배, feat

#87 Feature/splash check fix
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/item_on_boarding.xml
Labels: 현배, fix

#88 Feature/subway route
  app/build.gradle.kts
  app/src/main/java/com/timi/seulseul/data/api/SubwayRouteService.kt
  app/src/main/java/com/timi/seulseul/data/model/response/SubwayRouteResponse.kt
  app/src/main/java/com/timi/seulseul/data/repository/SubwayRouteRepo.kt
  app/src/main/java/com/timi/seulseul/di/AppModule.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/common/adapter/BindingAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/location/adapter/BindingAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/main/adapter/SubwayRouteAdapter.kt
  app/src/main/java/com/timi/seulseul/presentation/main/adapter/SubwayRouteItem.kt
  app/src/main/res/drawable/ic_alarm_setting_check.xml
  app/src/main/res/drawable/ic_home_day_unchecked.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_location_detail.xml
  app/src/main/res/layout/item_subway_body_info.xml
  app/src/main/res/layout/item_subway_footer.xml
  app/src/main/res/layout/item_subway_header.xml
  app/src/main/res/layout/item_subway_total_time.xml
  app/src/main/res/layout/item_subway_transfer.xml
Labels: 예빈, feat, ui

#91 Feature/permission dialog ui
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
  app/src/main/res/layout/dialog_permission_request.xml
Labels: 명지, ui

#93 Feature/permission check
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
Labels: 명지, feat

#95 Feature/get base route id
  app/src/main/java/com/timi/seulseul/data/model/LastSubwayArriveTime.kt
  app/src/main/java/com/timi/seulseul/data/model/LastSubwayDepartTime.kt
  app/src/main/java/com/timi/seulseul/data/model/Location.kt
  app/src/main/java/com/timi/seulseul/data/model/RealDayInfo.kt
  app/src/main/java/com/timi/seulseul/data/model/TodayTime.kt
  app/src/main/java/com/timi/seulseul/data/model/request/AlarmPatchRequest.kt
  app/src/main/java/com/timi/seulseul/data/model/request/AlarmPostRequest.kt
  app/src/main/java/com/timi/seulseul/data/model/response/EndLocationData.kt
  app/src/main/java/com/timi/seulseul/data/model/response/GetEndLocationData.kt
  app/src/main/java/com/timi/seulseul/data/service/LocationService.kt
  app/src/main/java/com/timi/seulseul/presentation/MainActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/MainViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/activity/LocationDetailActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/location/viewmodel/LocationDetailViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionActivity.kt
  app/src/main/java/com/timi/seulseul/presentation/permission/PermissionViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: 예빈, 명지, feat, fix
